In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
from gflownet.gflownet import GFlowNet
from policy import ForwardPolicy, BackwardPolicy
from setGenerationEnv import SetGenerationEnv
from gflownet.utils import trajectory_balance_loss
from torch.optim import Adam
from tqdm import tqdm
import torch 

In [39]:
bcz_size = 2
size = 4
nActions = 4
setEnv = SetGenerationEnv(size, nActions)

s0 = torch.zeros(bcz_size, size).float()
actions = torch.tensor([5, 3])

s = setEnv.update(s0, actions)
print(s)
actions = torch.tensor([0, 1])
s = setEnv.update(s, actions)
print(s)

tensor([[2., 0., 0., 0.],
        [4., 0., 0., 0.]])
tensor([[1., 2., 0., 0.],
        [2., 4., 0., 0.]])


In [40]:
s[0][0] = 1
s[0][2] = 3
s[0][3] = 2
print(s)

setEnv.mask(s)

tensor([[1., 2., 3., 2.],
        [2., 4., 0., 0.]])


tensor([[0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [41]:
backward_policy = BackwardPolicy(setEnv.state_dim, num_actions=setEnv.num_actions)
backward_policy(s)

tensor([[0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5000, 0.0000]])

In [42]:
forward_policy = ForwardPolicy(setEnv.state_dim, hidden_dim=32, num_actions=setEnv.num_actions)
forward_policy(s)

tensor([[0.0580, 0.1341, 0.1712, 0.0741, 0.0706, 0.2430, 0.0452, 0.0934, 0.1105],
        [0.0685, 0.0918, 0.1237, 0.1093, 0.1837, 0.1814, 0.0506, 0.0992, 0.0918]],
       grad_fn=<SoftmaxBackward0>)